name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet publish -c Release -o ./publish

      - name: Kill existing .NET Core App
        uses: appleboy/ssh-action@master
        with:
          host: 13.203.192.152
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill dotnet || true

      - name: Clean publish folder on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.203.192.152
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /home/ec2-user/publish/*

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 13.203.192.152
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./publish/*"
          target: "/home/ec2-user/publish"

      - name: Restart .NET Core App
        uses: appleboy/ssh-action@master
        with:
          host: 13.203.192.152
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/publish
            if [ -f "EmployeeManagementSystem.Server.dll" ]; then
              chmod +x EmployeeManagementSystem.Server.dll
              export ASPNETCORE_ENVIRONMENT=Development
              nohup dotnet EmployeeManagementSystem.Server.dll > output.log 2>&1 &
              sleep 5
              tail -n 50 output.log
            else
              echo "EmployeeManagementSystem.Server.dll not found in /home/ec2-user/publish"
              ls -la /home/ec2-user/publish
            fi
